// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    MattermostDTO,
} from '../models';

export interface SendToMattermostRequest {
    mattermostDTO?: MattermostDTO;
}

/**
 * no description
 */
export class DebugNotificationControllerApi extends BaseAPI {

    /**
     * ---there is no description defined---
     * sendToMattermost
     */
    sendToMattermost({ mattermostDTO }: SendToMattermostRequest): Observable<void>
    sendToMattermost({ mattermostDTO }: SendToMattermostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    sendToMattermost({ mattermostDTO }: SendToMattermostRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'X-JSC-TOKEN': this.configuration.apiKey('X-JSC-TOKEN') }), // ApiKeyAuth authentication
        };

        return this.request<void>({
            url: '/debug/sendToMattermost',
            method: 'POST',
            headers,
            body: mattermostDTO,
        }, opts?.responseOpts);
    };

}
