// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';

/**
 * no description
 */
export class SystemControllerApi extends BaseAPI {

    /**
     * ---there is no description defined---
     * getRegion
     */
    getRegion(): Observable<void>
    getRegion(opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    getRegion(opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        const headers: HttpHeaders = {
            ...(this.configuration.apiKey && { 'X-JSC-TOKEN': this.configuration.apiKey('X-JSC-TOKEN') }), // ApiKeyAuth authentication
        };

        return this.request<void>({
            url: '/region',
            method: 'GET',
            headers,
        }, opts?.responseOpts);
    };

}
