// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    WebSocketRoomUpdateRequestDTO,
} from '../models';

export interface TriggerRoomUpdateRequest {
    webSocketRoomUpdateRequestDTO?: WebSocketRoomUpdateRequestDTO;
}

/**
 * no description
 */
export class WebSocketControllerApi extends BaseAPI {

    /**
     * ---there is no description defined---
     * triggerRoomUpdate
     */
    triggerRoomUpdate({ webSocketRoomUpdateRequestDTO }: TriggerRoomUpdateRequest): Observable<void>
    triggerRoomUpdate({ webSocketRoomUpdateRequestDTO }: TriggerRoomUpdateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>
    triggerRoomUpdate({ webSocketRoomUpdateRequestDTO }: TriggerRoomUpdateRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
            ...(this.configuration.apiKey && { 'X-JSC-TOKEN': this.configuration.apiKey('X-JSC-TOKEN') }), // ApiKeyAuth authentication
        };

        return this.request<void>({
            url: '/web-socket/room/trigger-update',
            method: 'POST',
            headers,
            body: webSocketRoomUpdateRequestDTO,
        }, opts?.responseOpts);
    };

}
