// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    PropertyDTO,
    SessionDTO,
} from './';

/**
 * ---there is no description defined---
 * @export
 * @interface FrontendSessionDTO
 */
export interface FrontendSessionDTO {
    /**
     * @type {SessionDTO}
     * @memberof FrontendSessionDTO
     */
    session?: SessionDTO;
    /**
     * 
     * @type {Array<PropertyDTO>}
     * @memberof FrontendSessionDTO
     */
    appProperties?: Array<PropertyDTO>;
    /**
     * 
     * @type {string}
     * @memberof FrontendSessionDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof FrontendSessionDTO
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof FrontendSessionDTO
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof FrontendSessionDTO
     */
    modifiedBy?: string;
}
