// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Class PasswordResetDTO
 * @export
 * @interface PasswordResetDTO
 */
export interface PasswordResetDTO {
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    username?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PasswordResetDTO
     */
    sendMail?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PasswordResetDTO
     */
    modifiedBy?: string;
}
