// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @interface PropertyDTO
 */
export interface PropertyDTO {
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    key?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    value?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof PropertyDTO
     */
    modifiedBy?: string;
}
