// tslint:disable
/**
 * OpenApi Juwelo documentation
 * Specs for microservices: SystemController,SessionController,LoginController,UserController,WebSocketController,DebugNotificationController
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: development@juwelo.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * ---there is no description defined---
 * @export
 * @interface WebSocketRoomUpdateRequestDTO
 */
export interface WebSocketRoomUpdateRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    room?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    payload?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    createdBy?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    modifiedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof WebSocketRoomUpdateRequestDTO
     */
    modifiedBy?: string;
}
